In [2]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
from sklearn.model_selection import KFold
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score

%matplotlib inline

a) Reading the dataset in file1.csv into a pandas dataframe.

ans)

In [3]:
Body_measurements = pd.read_csv('https://raw.githubusercontent.com/Saurabh9687/Machine-Learning/main/file1.csv',encoding='unicode_escape', index_col=False, header=None)
Body_measurements.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,42.9,26.0,31.5,13.1,10.4,18.8,14.1,106.2,71.5,32.5,26.0,34.5,36.5,23.5,16.5,21,1,65.6
1,43.7,28.5,33.5,14.0,11.8,20.6,15.1,110.5,79.0,34.4,28.0,36.5,37.5,24.5,17.0,23,1,71.8
2,40.1,28.2,33.3,13.9,10.9,19.7,14.1,115.1,83.2,33.4,28.8,37.0,37.3,21.9,16.9,28,1,80.7
3,44.3,29.9,34.0,13.9,11.2,20.9,15.0,104.5,77.8,31.0,26.2,37.0,34.8,23.0,16.6,23,1,72.6
4,41.0,26.8,32.2,14.9,10.6,17.8,14.0,107.5,78.0,36.0,29.0,34.5,35.0,22.0,16.5,23,1,71.0

Description

In [4]:
import urllib.request
Body_measurements_description = urllib.request.urlopen('https://raw.githubusercontent.com/Saurabh9687/Machine-Learning/main/desc1.txt.txt')

for line in Body_measurements_description:
  decoded_line = line.decode('utf-8')
  print(decoded_line)

Body measurements of 446 physically active individuals.



Description

Body girth measurements and skeletal diameter measurements, as well as age, weight and gender, are given for 446 physically active individuals - 223 men and 223 women.



Format

A data frame with 446 observations on the following 18 variables.



attr1

A numerical vector, respondent's biacromial diameter in centimeters.



attr2

A numerical vector, respondent's biiliac diameter (pelvic breadth) in centimeters.



attr3

A numerical vector, respondent's bitrochanteric diameter in centimeters.



attr4

A numerical vector, respondent's elbow diameter in centimeters, measured as sum of two elbows.



attr5

A numerical vector, respondent's wrist diameter in centimeters, measured as sum of two wrists.



attr6

A numerical vector, respondent's knee diameter in centimeters, measured as sum of two knees.



attr7

A numerical vector, respondent's ankle diameter in centimeters, measured as sum of two ankles.



attr8

A numerical vector, respondent's shoulder girth in centimeters, measured over deltoid muscles.



attr9

A numerical vector, respondent's waist girth in centimeters, measured at the narrowest part of torso below the rib cage as average of contracted and relaxed position.



attr10

A numerical vector, respondent's bicep girth in centimeters, measured when flexed as the average of right and left girths.



attr11

A numerical vector, respondent's forearm girth in centimeters, measured when extended, palm up as the average of right and left girths.



attr12

A numerical vector, respondent's knee girth in centimeters, measured as sum of two knees.



attr13

A numerical vector, respondent's calf maximum girth in centimeters, measured as average of right and left girths.



attr14

A numerical vector, respondent's ankle minimum girth in centimeters, measured as average of right and left girths.



attr15

A numerical vector, respondent's wrist minimum girth in centimeters, measured as average of right and left girths.



attr16

A numerical vector, respondent's age in years.



attr17

A categorical vector, 1 if the respondent is male, 0 if female.



attr18

A numerical vector, respondent's weight in kilograms.

b) Replacing the column names of data frame with meaningful column names, using
the description in desc1.txt.

ans)

In [5]:
Body_measurements.columns = ['Biacromial dia','Biiliac dia','Bitrochanteric dia','Elbow dia','Wrist dia','Knee dia','Ankle dia','Shoulder girth','Waist girth','Bicep girth','Forearm girth','Knee girth','Calf girth ','Ankle girth','Wrist girth','Age','Sex','Weight']
Body_measurements.head()

,Biacromial dia,Biiliac dia,Bitrochanteric dia,Elbow dia,Wrist dia,Knee dia,Ankle dia,Shoulder girth,Waist girth,Bicep girth,Forearm girth,Knee girth,Calf girth,Ankle girth,Wrist girth,Age,Sex,Weight
0,42.9,26.0,31.5,13.1,10.4,18.8,14.1,106.2,71.5,32.5,26.0,34.5,36.5,23.5,16.5,21,1,65.6
1,43.7,28.5,33.5,14.0,11.8,20.6,15.1,110.5,79.0,34.4,28.0,36.5,37.5,24.5,17.0,23,1,71.8
2,40.1,28.2,33.3,13.9,10.9,19.7,14.1,115.1,83.2,33.4,28.8,37.0,37.3,21.9,16.9,28,1,80.7
3,44.3,29.9,34.0,13.9,11.2,20.9,15.0,104.5,77.8,31.0,26.2,37.0,34.8,23.0,16.6,23,1,72.6
4,41.0,26.8,32.2,14.9,10.6,17.8,14.0,107.5,78.0,36.0,29.0,34.5,35.0,22.0,16.5,23,1,71.0

Showing all data

In [6]:
print(Body_measurements)

     Biacromial dia  Biiliac dia  Bitrochanteric dia  Elbow dia  Wrist dia  \
0              42.9         26.0                31.5       13.1       10.4
1              43.7         28.5                33.5       14.0       11.8
2              40.1         28.2                33.3       13.9       10.9
3              44.3         29.9                34.0       13.9       11.2
4              41.0         26.8                32.2       14.9       10.6
..              ...          ...                 ...        ...        ...
441            38.5         25.6                31.7       11.8       10.2
442            35.3         25.4                28.5       10.6       10.4
443            36.2         28.7                27.8       12.4       10.2
444            34.9         28.7                32.9       13.4       10.8
445            38.7         29.7                32.0       12.8       10.5

     Knee dia  Ankle dia  Shoulder girth  Waist girth  Bicep girth  \
0        18.8       14.1           106.2         71.5         32.5
1        20.6       15.1           110.5         79.0         34.4
2        19.7       14.1           115.1         83.2         33.4
3        20.9       15.0           104.5         77.8         31.0
4        17.8       14.0           107.5         78.0         36.0
..        ...        ...             ...          ...          ...
441      16.8       12.9            92.8         74.7         28.1
442      17.0       12.6            95.9         60.8         26.8
443      17.9       13.2            96.1         66.9         26.2
444      17.9       12.9            98.5         68.8         29.6
445      18.4       13.8           103.8         63.7         26.4

     Forearm girth  Knee girth  Calf girth   Ankle girth  Wrist girth  Age  \
0             26.0        34.5         36.5         23.5         16.5   21
1             28.0        36.5         37.5         24.5         17.0   23
2             28.8        37.0         37.3         21.9         16.9   28
3             26.2        37.0         34.8         23.0         16.6   23
4             29.0        34.5         35.0         22.0         16.5   23
..             ...         ...          ...          ...          ...  ...
441           23.1        34.4         32.7         20.9         15.2   19
442           22.8        34.4         33.1         21.0         15.4   31
443           22.6        35.0         35.2         22.4         15.2   34
444           25.1        34.4         35.0         21.0         15.9   34
445           23.0        36.5         34.1         21.3         15.0   24

     Sex  Weight
0      1    65.6
1      1    71.8
2      1    80.7
3      1    72.6
4      1    71.0
..   ...     ...
441    0    60.0
442    0    46.8
443    0    57.3
444    0    64.1
445    0    63.6

[446 rows x 18 columns]

c) Checking if any column in the dataframe contains any
missing value or not.

ans)

In [7]:
for col in Body_measurements.columns.values:
  # val = set(data[col])
  null_val = sum(pd.isna(Body_measurements[col]))
  print(col,' : ', str(Body_measurements[col].dtypes), str(null_val),' null values!')

Biacromial dia  :  float64 0  null values!
Biiliac dia  :  float64 0  null values!
Bitrochanteric dia  :  float64 0  null values!
Elbow dia  :  float64 0  null values!
Wrist dia  :  float64 0  null values!
Knee dia  :  float64 0  null values!
Ankle dia  :  float64 0  null values!
Shoulder girth  :  float64 0  null values!
Waist girth  :  float64 0  null values!
Bicep girth  :  float64 0  null values!
Forearm girth  :  float64 0  null values!
Knee girth  :  float64 0  null values!
Calf girth   :  float64 0  null values!
Ankle girth  :  float64 0  null values!
Wrist girth  :  float64 0  null values!
Age  :  int64 0  null values!
Sex  :  int64 0  null values!
Weight  :  float64 0  null values!

So, there isn't any missing value in dataframe.

In [8]:
# Body_measurements = Body_measurements.replace('?', np.nan)

In [9]:
# Body_measurements = Body_measurements.dropna() #dropping the nan values
# Body_measurements

In [10]:
Body_measurements = Body_measurements.astype(float)

d) Performing standardization of each column in the data frame and creating a new data frame.

ans)

In [11]:
Body_measurements_standardized = (Body_measurements - Body_measurements.mean()) / Body_measurements.std()
Body_measurements_standardized_data = Body_measurements_standardized.values
Body_measurements_standardized_data

array([[ 1.33545136, -0.80469909, -0.22217308, ..., -0.96853577,
         0.99887829, -0.25278458],
       [ 1.59756096,  0.33090335,  0.77670993, ..., -0.76115845,
         0.99887829,  0.20735624],
       [ 0.41806775,  0.19463105,  0.67682163, ..., -0.24271516,
         0.99887829,  0.86788096],
       ...,
       [-0.85971656,  0.42175154, -2.07010666, ...,  0.3794168 ,
        -0.99887829, -0.86877954],
       [-1.28564466,  0.42175154,  0.47704503, ...,  0.3794168 ,
        -0.99887829, -0.36410897],
       [-0.04062405,  0.87599252,  0.02754767, ..., -0.65746979,
        -0.99887829, -0.4012171 ]])

In [12]:
Body_measurements_standardized_data_df = pd.DataFrame(Body_measurements_standardized_data, columns = Body_measurements.columns)
Body_measurements_standardized_data_df

,Biacromial dia,Biiliac dia,Bitrochanteric dia,Elbow dia,Wrist dia,Knee dia,Ankle dia,Shoulder girth,Waist girth,Bicep girth,Forearm girth,Knee girth,Calf girth,Ankle girth,Wrist girth,Age,Sex,Weight
0,1.335451,-0.804699,-0.222173,-0.186075,-0.140547,0.020226,0.214426,-0.189144,-0.497447,0.343131,0.035890,-0.631196,0.160882,0.722286,0.286509,-0.968536,0.998878,-0.252785
1,1.597561,0.330903,0.776710,0.476076,1.319641,1.351138,1.010048,0.220316,0.169952,0.790262,0.741039,0.128624,0.506515,1.250038,0.643245,-0.761158,0.998878,0.207356
2,0.418068,0.194631,0.676822,0.402504,0.380949,0.685682,0.214426,0.658343,0.543696,0.554930,1.023098,0.318579,0.437389,-0.122117,0.571898,-0.242715,0.998878,0.867881
3,1.794143,0.966841,1.026431,0.402504,0.693846,1.572956,0.930486,-0.351024,0.063168,-0.009867,0.106405,0.318579,-0.426694,0.458410,0.357856,-0.761158,0.998878,0.266729
4,0.712941,-0.441306,0.127436,1.138227,0.068052,-0.719170,0.134863,-0.065354,0.080966,1.166793,1.093613,-0.631196,-0.357567,-0.069341,0.286509,-0.761158,0.998878,0.147983
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,-0.106151,-0.986395,-0.122285,-1.142516,-0.349145,-1.458565,-0.740321,-1.465136,-0.212690,-0.692330,-0.986576,-0.669187,-1.152523,-0.649868,-0.641006,-1.175913,-0.998878,-0.668396
442,-1.154590,-1.077244,-1.720498,-2.025385,-0.140547,-1.310686,-0.979008,-1.169944,-1.449602,-0.998261,-1.092348,-0.669187,-1.014270,-0.597093,-0.498311,0.068351,-0.998878,-1.648050
443,-0.859717,0.421752,-2.070107,-0.701082,-0.349145,-0.645230,-0.501634,-1.150899,-0.906785,-1.139461,-1.162863,-0.441241,-0.288441,0.141759,-0.641006,0.379417,-0.998878,-0.868780
444,-1.285645,0.421752,0.477045,0.034642,0.276650,-0.645230,-0.740321,-0.922363,-0.737710,-0.339332,-0.281427,-0.669187,-0.357567,-0.597093,-0.141575,0.379417,-0.998878,-0.364109
445,-0.040624,0.875993,0.027548,-0.406792,-0.036247,-0.275533,-0.024261,-0.417680,-1.191541,-1.092394,-1.021833,0.128624,-0.668637,-0.438768,-0.783700,-0.657470,-0.998878,-0.401217

e) Considering the weight attribute as the response variable and all other attributes as predictor variables.


f) Spliting the data into two sets such that 80% of the data is considered as set T1 and 20% of the
data is considered as set T2.

ans)

In [13]:
T1 = Body_measurements_standardized_data_df.sample(frac=0.8,random_state=20)
T2 = Body_measurements_standardized_data_df.drop(T1.index)

In [14]:
n_T1 = len(T1.index) 
print('number of data points in the training data set:',n_T1)
n_T2 = len(T2.index) 
print('number of data points in the testing data set:',n_T2)

number of data points in the training data set: 357
number of data points in the testing data set: 89

In [15]:
cols = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
X_T1 = T1[T1.columns[cols]]
X_T1

,Biacromial dia,Biiliac dia,Bitrochanteric dia,Elbow dia,Wrist dia,Knee dia,Ankle dia,Shoulder girth,Waist girth,Bicep girth,Forearm girth,Knee girth,Calf girth,Ankle girth,Wrist girth,Age,Sex
370,-1.121826,-0.350458,-1.470777,-1.289661,-1.392136,-0.423412,-1.376819,-0.969975,-0.586433,-0.904129,-0.951318,-0.213295,-1.912916,-1.072069,-1.069089,0.172039,-0.998878
228,-0.597607,0.103783,0.027548,-0.627510,-0.557743,-1.162807,-0.501634,-1.398480,-0.942379,-1.068861,-1.198120,-0.821151,-0.357567,0.458410,-1.140437,-0.761158,-0.998878
301,-0.007860,-0.259610,0.726766,-0.333220,0.485248,-0.423412,-0.342510,0.220316,0.125459,-0.198133,0.000632,0.318579,-0.288441,0.563961,0.072467,1.105237,-0.998878
160,-0.630371,-0.850123,-0.122285,1.064655,0.068052,0.463863,0.373550,0.696432,0.214446,0.837328,-0.034625,-0.213295,-0.323004,-0.174892,0.143814,0.172039,0.998878
181,0.811232,1.511930,1.475928,1.211800,1.111042,0.020226,1.566983,0.229838,2.857345,0.696129,1.164128,1.192372,0.852148,1.144487,0.928634,2.556879,0.998878
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409,-0.401025,-0.441306,-0.421950,-1.142516,-0.349145,-0.275533,-0.819883,-0.912841,-0.951278,-1.610125,-1.656467,-1.201061,-0.599511,-1.019294,-0.783700,-0.657470,-0.998878
443,-0.859717,0.421752,-2.070107,-0.701082,-0.349145,-0.645230,-0.501634,-1.150899,-0.906785,-1.139461,-1.162863,-0.441241,-0.288441,0.141759,-0.641006,0.379417,-0.998878
429,-1.580518,-0.850123,-1.271000,-1.436806,-0.974939,-1.606444,-0.979008,-1.255645,-0.862291,-0.409931,-0.986576,-0.213295,0.471952,0.194534,-1.211784,0.794171,-0.998878
304,-0.761425,-0.804699,-0.621726,-0.921799,-0.244846,-1.310686,-1.138132,-0.322457,-0.737710,-0.951195,-0.880803,-0.669187,-0.288441,-0.280442,-1.069089,-1.072224,-0.998878
244,-0.269970,0.830568,0.377157,0.255359,0.068052,2.016593,0.453112,0.306017,0.454709,0.343131,0.317949,1.648265,0.886711,0.458410,0.357856,-0.450092,-0.998878

In [16]:
X_T1_array = T1[T1.columns[cols]].to_numpy()
X_T1_array

array([[-1.12182616, -0.35045812, -1.47077685, ..., -1.06908925,
         0.17203948, -0.99887829],
       [-0.59760695,  0.10378286,  0.02754767, ..., -1.14043652,
        -0.76115845, -0.99887829],
       [-0.00786035, -0.25960992,  0.72676578, ...,  0.07246707,
         1.10523741, -0.99887829],
       ...,
       [-1.58051796, -0.85012319, -1.27100025, ..., -1.21178379,
         0.79417143, -0.99887829],
       [-0.76142546, -0.80469909, -0.62172629, ..., -1.06908925,
        -1.07222443, -0.99887829],
       [-0.26996995,  0.83056842,  0.37715673, ...,  0.35785615,
        -0.45009247, -0.99887829]])

In [17]:
X_T1 = np.hstack((X_T1_array, np.ones((X_T1_array.shape[0],1), dtype=X_T1_array.dtype)))
X_T1

array([[-1.12182616, -0.35045812, -1.47077685, ...,  0.17203948,
        -0.99887829,  1.        ],
       [-0.59760695,  0.10378286,  0.02754767, ..., -0.76115845,
        -0.99887829,  1.        ],
       [-0.00786035, -0.25960992,  0.72676578, ...,  1.10523741,
        -0.99887829,  1.        ],
       ...,
       [-1.58051796, -0.85012319, -1.27100025, ...,  0.79417143,
        -0.99887829,  1.        ],
       [-0.76142546, -0.80469909, -0.62172629, ..., -1.07222443,
        -0.99887829,  1.        ],
       [-0.26996995,  0.83056842,  0.37715673, ..., -0.45009247,
        -0.99887829,  1.        ]])

In [18]:
col = [17]
Y_T1 = T1[T1.columns[col]]
Y_T1

       Weight
370 -0.965261
228 -0.742612
301  0.118297
160  0.073767
181  1.862379
..        ...
409 -1.076585
443 -0.868780
429 -0.801985
304 -0.801985
244  1.001470

[357 rows x 1 columns]

In [19]:
Y_T1 = T1[T1.columns[col]].to_numpy()
Y_T1

array([[-9.65260678e-01],
       [-7.42611897e-01],
       [ 1.18296726e-01],
       [ 7.37669693e-02],
       [ 1.86237885e+00],
       [-2.97314333e-01],
       [ 7.37669693e-02],
       [-1.00236881e+00],
       [-8.31671409e-01],
       [-7.57455149e-01],
       [-1.58867727e+00],
       [-1.49961775e+00],
       [-6.68395636e-01],
       [ 1.29091364e+00],
       [-1.27696897e+00],
       [ 7.26870062e-01],
       [-1.09142832e+00],
       [ 2.37042742e-01],
       [ 3.40945507e-01],
       [ 1.05342161e+00],
       [ 1.99596812e+00],
       [-4.30903602e-01],
       [ 2.47095218e+00],
       [ 1.14990275e+00],
       [-9.20730922e-01],
       [ 9.49518844e-01],
       [ 1.29091364e+00],
       [ 8.23351201e-01],
       [-3.64108968e-01],
       [-4.45746855e-01],
       [-2.30519699e-01],
       [-1.36602849e+00],
       [-4.01217098e-01],
       [ 2.07356238e-01],
       [-1.02463369e+00],
       [ 2.22199490e-01],
       [ 9.86626974e-01],
       [-4.49291263e-04],
       [ 9.49518844e-01],
       [ 3.40945507e-01],
       [-1.51446101e+00],
       [-1.48477450e+00],
       [ 9.49518844e-01],
       [-8.31671409e-01],
       [ 1.25380551e+00],
       [ 5.48751037e-01],
       [ 8.67880957e-01],
       [ 1.12021624e+00],
       [ 1.25380551e+00],
       [-6.68395636e-01],
       [ 4.96799654e-01],
       [-7.46655518e-02],
       [-1.34038560e-01],
       [ 7.37669693e-02],
       [-4.30903602e-01],
       [-3.34422464e-01],
       [-1.50703938e+00],
       [ 4.89378028e-01],
       [-1.72226654e+00],
       [ 3.63210385e-01],
       [ 2.48579544e+00],
       [-1.12853645e+00],
       [-1.41055824e+00],
       [-1.08400670e+00],
       [-6.46130758e-01],
       [ 4.30005020e-01],
       [-1.26616934e-01],
       [ 2.44464369e-01],
       [-7.42611897e-01],
       [-1.41055824e+00],
       [ 5.48751037e-01],
       [ 1.87722210e+00],
       [ 1.25718352e-01],
       [ 3.11259003e-01],
       [ 1.10875100e-01],
       [ 1.22411901e+00],
       [-1.91522881e+00],
       [-1.05432019e+00],
       [-3.64108968e-01],
       [-2.97314333e-01],
       [-6.53552384e-01],
       [ 1.10875100e-01],
       [ 3.40945507e-01],
       [ 8.82724209e-01],
       [-1.02463369e+00],
       [ 1.29091364e+00],
       [ 1.02373510e+00],
       [-1.17306621e+00],
       [-5.19963115e-01],
       [ 2.74150873e-01],
       [ 4.44848272e-01],
       [-1.12111483e+00],
       [ 1.12021624e+00],
       [-2.82471081e-01],
       [-5.64492871e-01],
       [-1.21017434e+00],
       [ 1.40561604e-01],
       [-9.50417426e-01],
       [ 1.29091364e+00],
       [ 1.27607039e+00],
       [ 2.06276275e+00],
       [-1.00979043e+00],
       [ 2.44464369e-01],
       [ 9.49518844e-01],
       [ 3.11259003e-01],
       [-3.27000838e-01],
       [-4.45746855e-01],
       [-1.63725064e-01],
       [-3.01357955e-02],
       [ 6.97233479e-03],
       [-4.01217098e-01],
       [-3.34422464e-01],
       [-5.05119863e-01],
       [ 1.14990275e+00],
       [-7.72298401e-01],
       [-6.83238888e-01],
       [ 1.01631348e+00],
       [-6.83238888e-01],
       [ 1.43939608e-02],
       [-6.83238888e-01],
       [ 2.44464369e-01],
       [-4.01217098e-01],
       [ 2.74150873e-01],
       [-2.52784577e-01],
       [ 7.37669693e-02],
       [-1.07658507e+00],
       [-8.91044418e-01],
       [ 9.49518844e-01],
       [ 1.25380551e+00],
       [ 3.11259003e-01],
       [-1.41055824e+00],
       [-2.60206203e-01],
       [-1.00236881e+00],
       [-1.42540149e+00],
       [ 1.49129755e+00],
       [ 1.40561604e-01],
       [-2.23098073e-01],
       [ 6.45232176e-01],
       [ 2.22199490e-01],
       [ 2.51885995e-01],
       [ 4.30005020e-01],
       [ 6.97233479e-03],
       [ 1.45418942e+00],
       [ 4.67113150e-01],
       [-4.82854985e-01],
       [ 1.62488681e+00],
       [-1.79648280e+00],
       [ 1.25380551e+00],
       [ 1.34286502e+00],
       [ 2.74150873e-01],
       [-9.50417426e-01],
       [-1.27696897e+00],
       [-1.51446101e+00],
       [-4.01217098e-01],
       [ 8.82724209e-01],
       [ 5.41329411e-01],
       [-4.01217098e-01],
       [-8.01984905e-01],
       [ 1.49129755e+00],
       [-3.34422464e-01],
       [ 4.59691524e-01],
       [ 2.81572499e-01],
       [-5.19963115e-01],
       [ 4.96799654e-01],
       [-5.64492871e-01],
       [ 1.45418942e+00],
       [ 6.97233479e-03],
       [ 8.82724209e-01],
       [-1.67773678e+00],
       [-1.00236881e+00],
       [-9.05887670e-01],
       [ 3.51740146e+00],
       [ 1.35770828e+00],
       [-1.06916344e+00],
       [ 1.82527072e+00],
       [ 1.12021624e+00],
       [-9.72682304e-01],
       [ 1.29091364e+00],
       [ 1.18701088e+00],
       [-9.05887670e-01],
       [ 1.32060015e+00],
       [ 2.93851463e+00],
       [-7.87141653e-01],
       [-1.57383401e+00],
       [ 1.99596812e+00],
       [-1.15822296e+00],
       [-8.20871779e-02],
       [ 1.08310811e+00],
       [ 1.52840568e+00],
       [-1.08400670e+00],
       [ 7.86243071e-01],
       [ 1.89206535e+00],
       [ 4.44848272e-01],
       [-1.71484491e+00],
       [ 2.37042742e-01],
       [ 4.07740142e-01],
       [ 2.41900080e+00],
       [-1.03947694e+00],
       [-1.03947694e+00],
       [ 8.15929575e-01],
       [ 1.49129755e+00],
       [-8.16828157e-01],
       [-7.72298401e-01],
       [-4.30903602e-01],
       [-4.82854985e-01],
       [-7.87091732e-03],
       [-9.69304300e-02],
       [ 1.62488681e+00],
       [-1.02463369e+00],
       [-7.94563279e-01],
       [ 1.01631348e+00],
       [-2.30519699e-01],
       [ 1.92512986e-01],
       [-1.39571499e+00],
       [-4.16060350e-01],
       [-1.17306621e+00],
       [-1.26616934e-01],
       [-7.72298401e-01],
       [ 1.62488681e+00],
       [ 1.63973007e+00],
       [-7.05503766e-01],
       [ 3.92896890e-01],
       [ 4.81956402e-01],
       [ 8.53037705e-01],
       [-1.25470409e+00],
       [ 8.82724209e-01],
       [ 6.97233479e-03],
       [ 6.15545671e-01],
       [-4.68011733e-01],
       [ 2.07356238e-01],
       [-1.03947694e+00],
       [ 1.05342161e+00],
       [-1.14337970e+00],
       [-6.38709132e-01],
       [-7.87141653e-01],
       [ 1.79558421e+00],
       [-1.41055824e+00],
       [ 1.59520031e+00],
       [ 2.59307621e-01],
       [-4.68011733e-01],
       [ 2.22199490e-01],
       [-1.63725064e-01],
       [ 1.29091364e+00],
       [ 2.44464369e-01],
       [-9.20730922e-01],
       [-1.11369320e+00],
       [-1.46993125e+00],
       [-9.72682304e-01],
       [-9.20730922e-01],
       [-1.20275271e+00],
       [-1.67031515e+00],
       [ 1.18296726e-01],
       [-6.01601002e-01],
       [-7.35190271e-01],
       [ 7.49134940e-01],
       [ 5.63594289e-01],
       [ 1.69168145e+00],
       [ 5.78437541e-01],
       [-3.01357955e-02],
       [ 1.40561604e-01],
       [ 2.60454145e+00],
       [-4.97698237e-01],
       [ 1.66199495e+00],
       [ 1.22411901e+00],
       [ 9.49518844e-01],
       [ 2.92372130e-02],
       [ 1.18701088e+00],
       [-2.30519699e-01],
       [ 8.30772827e-01],
       [ 6.52653802e-01],
       [ 6.15545671e-01],
       [-6.16444254e-01],
       [-1.14337970e+00],
       [ 1.01631348e+00],
       [ 1.06826486e+00],
       [-4.97698237e-01],
       [ 6.45232176e-01],
       [-1.46993125e+00],
       [-7.12925393e-01],
       [ 4.81956402e-01],
       [-2.08254821e-01],
       [ 6.97233479e-03],
       [ 7.78821444e-01],
       [ 7.34291688e-01],
       [ 8.15929575e-01],
       [-1.64805028e+00],
       [ 2.59307621e-01],
       [-3.78952220e-01],
       [ 1.28349202e+00],
       [ 7.78821444e-01],
       [ 1.78074096e+00],
       [ 3.40945507e-01],
       [ 1.75847608e+00],
       [-4.01217098e-01],
       [ 1.79558421e+00],
       [-5.19963115e-01],
       [-1.14337970e+00],
       [-5.86757750e-01],
       [-1.63725064e-01],
       [-1.63725064e-01],
       [-4.16060350e-01],
       [ 1.66199495e+00],
       [ 4.81956402e-01],
       [ 5.78437541e-01],
       [ 1.05342161e+00],
       [-1.63725064e-01],
       [ 1.10875100e-01],
       [ 3.40945507e-01],
       [-3.12157586e-01],
       [-3.64108968e-01],
       [ 3.03837377e-01],
       [-1.26616934e-01],
       [-6.83238888e-01],
       [ 2.07356238e-01],
       [ 6.45232176e-01],
       [-9.94947183e-01],
       [-1.93411569e-01],
       [ 1.17216763e+00],
       [ 3.40945507e-01],
       [-1.63320702e+00],
       [-8.76201166e-01],
       [ 7.12026810e-01],
       [-8.16828157e-01],
       [-9.35574174e-01],
       [-9.05887670e-01],
       [ 2.96415751e-01],
       [-1.52925434e-02],
       [-1.93411569e-01],
       [-2.00428833e+00],
       [ 2.22199490e-01],
       [ 1.79558421e+00],
       [-1.78163954e+00],
       [-9.72682304e-01],
       [ 1.22411901e+00],
       [ 8.53037705e-01],
       [-1.39571499e+00],
       [ 9.49518844e-01],
       [-3.41844090e-01],
       [ 3.11259003e-01],
       [-1.02463369e+00],
       [-4.30903602e-01],
       [ 1.12021624e+00],
       [ 6.15545671e-01],
       [-5.98222997e-02],
       [-6.01601002e-01],
       [-7.42611897e-01],
       [-9.69304300e-02],
       [ 4.81956402e-01],
       [ 2.44464369e-01],
       [-7.27768645e-01],
       [-1.07658507e+00],
       [-1.23986084e+00],
       [-1.07658507e+00],
       [-8.68779540e-01],
       [-8.01984905e-01],
       [-8.01984905e-01],
       [ 1.00147023e+00]])

g) Performing ℓ1 regularized least squares regression, choosing regularization constant
λ ∈ {10−5, 10−4, 10−3, 10−2, 10−1, 1, 10, 100, 1000, 10000} using a 5-fold cross-validation on the
full train set T1. Using average R2 scores of the folds as the criterion to choose best regularization
parameter λ⋆. Performing ℓ1 regularized least squares regression with best regularization parameter
λ⋆ obtained from the cross-validation procedure on the set T1 and obtaining the regression
coefficients.

ans)

In [20]:
X = T1.iloc[:,:-1]
y = T1.iloc[:,-1]

lambdas = [1e-5,1e-4,1e-3,1e-2,1e-1,1,10,100,1000,10000]
R2_list = []

kf = KFold(n_splits=5)
for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    fold_scores = []
    for l in lambdas:
        model = Lasso(alpha=l, fit_intercept=True)
        model.fit(X_train, y_train)

        y_pred = model.predict(X_test)
        fold_scores.append(r2_score(y_test, y_pred))
        
    R2_list.append(fold_scores)

mean_R2 = np.mean(R2_list, axis=0)

best_lambda_index = np.argmax(mean_R2)
best_lambda = lambdas[best_lambda_index]

model = Lasso(alpha=best_lambda, fit_intercept=True)
model.fit(X, y)

beeta = model.coef_
print( "\n Mean R^2 = ", mean_R2, "\n********************","\n Best Lambda = ", best_lambda, "\n********************"," \n Beeta = ", beeta)

 Mean R^2 =  [ 0.94525076  0.945333    0.94600147  0.94417455  0.92210066 -0.00754538
 -0.00754538 -0.00754538 -0.00754538 -0.00754538]
********************
 Best Lambda =  0.001
********************
 Beeta =  [ 3.55099889e-02  5.77313104e-02  5.62976705e-02  7.80267632e-02
  3.08217087e-02  2.19514759e-05  6.15357773e-02  1.83945130e-01
  4.10751706e-01  1.09481633e-01  1.28129705e-02  1.40812660e-01
  7.16156980e-02  0.00000000e+00 -0.00000000e+00 -8.20213220e-02
 -9.66504794e-02]

h) From the regression coefficients obtained, indicating the relative importance of each
attribute in predicting the response variable using the magnitude and sign of the regression coefficients.
Also comparing the regression coefficients
with those obtained in Question 2.

ans)

In [21]:
beeta_sorted = sorted(beeta, key = lambda x:abs(x), reverse=True)
beeta_sorted

[0.41075170559819746,
 0.18394512983139227,
 0.14081266012063354,
 0.1094816330660091,
 -0.09665047940867504,
 -0.0820213219569712,
 0.07802676321463325,
 0.07161569795396723,
 0.06153577732114409,
 0.05773131043368309,
 0.05629767048551185,
 0.03550998889753514,
 0.030821708731967615,
 0.012812970535229328,
 2.1951475920778376e-05,
 0.0,
 -0.0]

So, from the regression coefficient to indicate the relative importance of each
attribute in predicting the response variable, we sort regression coefficient in non-increasing manner which will decide their importance. Also Attributes are ranked in their importance order below.

In [23]:
d_list = []
for i in range(len(beeta_sorted)):
  index_attribute = np.where(beeta == beeta_sorted[i])
  print(i+1," Attribute = ",Body_measurements.columns[index_attribute[0][0]], ", Beeta value = ",beeta_sorted[i])
  d_list.append(Body_measurements.columns[index_attribute[0][0]])
  if beeta_sorted[i] == 0 :
    Body_measurements = Body_measurements.drop(columns=Body_measurements.columns[index_attribute[0][0]])

1  Attribute =  Waist girth , Beeta value =  0.41075170559819746
2  Attribute =  Shoulder girth , Beeta value =  0.18394512983139227
3  Attribute =  Knee girth , Beeta value =  0.14081266012063354
4  Attribute =  Bicep girth , Beeta value =  0.1094816330660091
5  Attribute =  Sex , Beeta value =  -0.09665047940867504
6  Attribute =  Age , Beeta value =  -0.0820213219569712
7  Attribute =  Elbow dia , Beeta value =  0.07802676321463325
8  Attribute =  Calf girth  , Beeta value =  0.07161569795396723
9  Attribute =  Ankle dia , Beeta value =  0.06153577732114409
10  Attribute =  Biiliac dia , Beeta value =  0.05773131043368309
11  Attribute =  Bitrochanteric dia , Beeta value =  0.05629767048551185
12  Attribute =  Biacromial dia , Beeta value =  0.03550998889753514
13  Attribute =  Wrist dia , Beeta value =  0.030821708731967615
14  Attribute =  Forearm girth , Beeta value =  0.012812970535229328
15  Attribute =  Knee dia , Beeta value =  2.1951475920778376e-05
16  Attribute =  Ankle girth , Beeta value =  0.0
17  Attribute =  Wrist girth , Beeta value =  -0.0

**Yes, there are two of the coefficients that are zero which are Ankle girth and Wrist girth.**

**Regression coefficients obtained from Q3(L1 regularization) and Q2 (L2 regularization) are different in the sense that some regression coefficients of Q3 (L1 regularization) are zeros so these are sparse coefficients, whereas regression coefficients of Q2 (L2 regularization) are small but non-zero coefficients. So L1 regularization encourages the absolute values of the coefficients to be small, whereas L2 regularization encourages the square of the coefficients to be small. So we can see that L1 is better for feature selection by eliminating less important features and L2 is better for preventing overfitting.**